// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdgyfnswoomhiezkxtrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZ3lmbnN3b29taGllemt4dHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0OTEyNzMsImV4cCI6MjA3NTA2NzI3M30.fFSt5cn1uD9bWlnnIsjUsvx9sMdEM8eCiPUhG08Fqjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});